In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
crime_anal_police = pd.read_csv('C:\myPyCode\data\crime_in_Seoul.csv', thousands=',', encoding='euc-kr')
crime_anal_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

In [ ]:
# 서울시 지역구 경찰서 목록
police = [서울특별시경찰청
101경비단
202경비단
서울강남경찰서
서울강동경찰서
서울강북경찰서
서울강서경찰서
서울관악경찰서
서울광진경찰서
서울구로경찰서
국회경비대
서울금천경찰서
서울남대문경찰서
서울노원경찰서
서울도봉경찰서
서울동대문경찰서
서울동작경찰서
서울마포경찰서
서울방배경찰서
서울서대문경찰서
서울서부경찰서
서울서초경찰서
서울성동경찰서
서울성북경찰서
서울송파경찰서
서울수서경찰서
서울양천경찰서
서울영등포경찰서
서울용산경찰서
서울은평경찰서
정부서울청사경비대
서울종로경찰서
서울종암경찰서
서울중랑경찰서
서울중부경찰서
서울지하철경찰대
서울혜화경찰서]

In [ ]:
# google api 키 : AIzaSyDiJXlcNbyL9LCpgFhu_cbo31uDsZ15Cqo

In [3]:
import googlemaps

In [4]:
gmaps_key = 'AIzaSyDiJXlcNbyL9LCpgFhu_cbo31uDsZ15Cqo'
gmaps = googlemaps.Client(key=gmaps_key)

In [5]:
gmaps.geocode('서울동작경찰서', language='ko')

[{'address_components': [{'long_name': '１４８',
    'short_name': '１４８',
    'types': ['premise']},
   {'long_name': '노량진로',
    'short_name': '노량진로',
    'types': ['political', 'sublocality', 'sublocality_level_4']},
   {'long_name': '동작구',
    'short_name': '동작구',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '156-051',
    'short_name': '156-051',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 동작구 노량진로 148',
  'geometry': {'location': {'lat': 37.5130866, 'lng': 126.9428498},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': 37.5144355802915,
     'lng': 126.9441987802915},
    'southwest': {'lat': 37.51173761970851, 'lng': 126.9415008197085}}},
  'partial_match': True,
  'place_id': 'ChIJB3ImbmiffDUR7BOlDuasX44',
  'plus_code': {'compound_code': 'GW7V+64 대한민국 서울특별시',
   'global_code': '8Q98GW7V+64'},
  'types': ['establishment', 'point_of_interest', 'police']}]

In [7]:
station_name= []

for name in crime_anal_police['관서명']:
    station_name.append('서울시 '+str(name[0:-1])+"경찰서")
    
station_name

['서울시 중부경찰서',
 '서울시 종로경찰서',
 '서울시 남대문경찰서',
 '서울시 서대문경찰서',
 '서울시 혜화경찰서',
 '서울시 용산경찰서',
 '서울시 성북경찰서',
 '서울시 동대문경찰서',
 '서울시 마포경찰서',
 '서울시 영등포경찰서',
 '서울시 성동경찰서',
 '서울시 동작경찰서',
 '서울시 광진경찰서',
 '서울시 서부경찰서',
 '서울시 강북경찰서',
 '서울시 금천경찰서',
 '서울시 중랑경찰서',
 '서울시 강남경찰서',
 '서울시 관악경찰서',
 '서울시 강서경찰서',
 '서울시 강동경찰서',
 '서울시 종암경찰서',
 '서울시 구로경찰서',
 '서울시 서초경찰서',
 '서울시 양천경찰서',
 '서울시 송파경찰서',
 '서울시 노원경찰서',
 '서울시 방배경찰서',
 '서울시 은평경찰서',
 '서울시 도봉경찰서',
 '서울시 수서경찰서']

In [17]:
station_address = []
station_lat = []
station_lng = []

for name in station_name:
    tmp = gmaps.geocode(name, language='ko')
    station_address.append(tmp[0].get('formatted_address'))
    
    tmp_loc = tmp[0].get('geometry')
    station_lat.append(tmp_loc['location']['lat'])
    station_lng.append(tmp_loc['location']['lng'])
    print(name + "-->" + tmp[0].get('formatted_address'))

서울시 중부경찰서-->대한민국 서울특별시 중구 수표로 27
서울시 종로경찰서-->대한민국 서울특별시 종로구 인사동5길 41
서울시 남대문경찰서-->대한민국 서울특별시 중구 한강대로 410
서울시 서대문경찰서-->대한민국 서울특별시 서대문구 통일로 113
서울시 혜화경찰서-->대한민국 서울특별시 종로구 창경궁로 112-16
서울시 용산경찰서-->대한민국 서울특별시 용산구 백범로 329
서울시 성북경찰서-->대한민국 서울특별시 성북구 삼선동 보문로 170
서울시 동대문경찰서-->대한민국 서울특별시 동대문구 약령시로21길 29
서울시 마포경찰서-->대한민국 서울특별시 마포구 마포대로 183
서울시 영등포경찰서-->대한민국 서울특별시 영등포구 국회대로 608
서울시 성동경찰서-->대한민국 서울특별시 성동구

IndexError: list index out of range

In [14]:
station_address

['대한민국 서울특별시 중구 수표로 27',
 '대한민국 서울특별시 종로구 인사동5길 41',
 '대한민국 서울특별시 중구 한강대로 410',
 '대한민국 서울특별시 서대문구 통일로 113',
 '대한민국 서울특별시 종로구 창경궁로 112-16',
 '대한민국 서울특별시 용산구 백범로 329',
 '대한민국 서울특별시 성북구 삼선동 보문로 170',
 '대한민국 서울특별시 동대문구 약령시로21길 29',
 '대한민국 서울특별시 마포구 마포대로 183',
 '대한민국 서울특별시 영등포구 국회대로 608',
 '대한민국 서울특별시 성동구']

In [15]:
station_lat

[37.56361709999999,
 37.571824,
 37.5547584,
 37.5647439,
 37.5719679,
 37.5387099,
 37.58977830000001,
 37.58506149999999,
 37.550814,
 37.5260441,
 37.5633415]

In [16]:
station_lng

[126.9896517,
 126.9841533,
 126.9734981,
 126.9667705,
 126.9989574,
 126.9659183,
 127.016589,
 127.0457679,
 126.954028,
 126.9008091,
 127.0371025]

In [19]:
gu_name = []

for name in station_address:
    tmp = name.split()
    tmp_gu = [gu for gu in tmp if gu[-1] == '구'][0]
    
    gu_name.append(tmp_gu)
    
crime_anal_police['구별'] = gu_name
crime_anal_police.head()

ValueError: Length of values (11) does not match length of index (31)

In [95]:
crime_anal_police.loc[crime_anal_police['관서명']=='도봉서',['구별']]='도봉구'

In [96]:
crime_anal_police.head(30)

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,남대문구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구
5,용산서,5,5,14,14,194,173,1557,587,2050,1704,용산구
6,성북서,2,2,2,1,86,71,953,409,1194,1015,성북구
7,동대문서,5,5,13,13,173,146,1981,814,2548,2227,동대문구
8,마포서,8,8,14,10,294,247,2555,813,2983,2519,마포구
9,영등포서,14,12,22,20,295,183,2964,978,3572,2961,영등포구
10,성동서,4,4,9,8,126,119,1607,597,1612,1395,성동구
11,동작서,5,5,9,5,285,139,1865,661,1910,1587,동작구
12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,광진구
13,서부서,2,2,2,1,70,59,819,293,1192,1038,은평구
14,강북서,7,8,14,13,153,126,1434,618,2649,2348,강북구
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구
16,중랑서,13,12,11,9,187,148,2135,829,2847,2407,중랑구
17,강남서,3,3,15,12,300,225,2411,984,2465,2146,강남구
18,관악서,9,8,12,14,320,221,2706,827,3298,2642,관악구
19,강서서,7,8,13,13,262,191,2096,1260,3207,2718,강서구
20,강동서,4,3,6,8,156,123,2366,789,2712,2248,강동구
21,종암서,3,3,3,3,64,53,832,332,1015,840,성북구
22,구로서,8,6,15,11,281,164,2335,889,3007,2432,구로구
23,서초서,7,4,8,5,334,193,1982,905,1852,1607,서초구
24,양천서,3,5,6,3,120,105,1890,672,2509,2030,양천구
25,송파서,11,10,13,10,220,178,3239,1129,3295,2786,송파구
26,노원서,10,10,7,7,197,121,2193,801,2723,2329,노원구
27,방배서,1,2,1,1,59,56,653,186,547,491,서초구
28,은평서,1,1,7,5,96,82,1095,418,1461,1268,은평구
29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,도봉구

In [97]:
crime_anal_police.to_csv('C:\myPyCode\data\crime_in_Seoul_include_gu_name.csv',sep=",", encoding='utf-8')

In [99]:
crime_anal_raw = pd.read_csv('C:\myPyCode\data\crime_in_Seoul_include_gu_name.csv', encoding='utf-8')
crime_anal_raw.head()

,Unnamed: 0,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,2,남대문서,1,0,6,4,65,46,1153,382,869,794,남대문구
3,3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [101]:
crime_anal_raw = pd.read_csv('C:\myPyCode\data\crime_in_Seoul_include_gu_name.csv', encoding='utf-8', index_col=0)
crime_anal = pd.pivot_table(crime_anal_raw, index = '구별', aggfunc=np.sum)
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    225    300     12     15      3      3    984   2411   2146   2465
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
강서구    191    262     13     13      8      7   1260   2096   2718   3207
관악구    221    320     14     12      8      9    827   2706   2642   3298

In [103]:
crime_anal['강간검거율'] = crime_anal['강간 검거']/crime_anal['강간 발생']*100
crime_anal['강도검거율'] = crime_anal['강도 검거']/crime_anal['강도 발생']*100
crime_anal['살인검거율'] = crime_anal['살인 검거']/crime_anal['살인 발생']*100
crime_anal['절도검거율'] = crime_anal['절도 검거']/crime_anal['절도 발생']*100
crime_anal['폭력검거율'] = crime_anal['폭력 검거']/crime_anal['폭력 발생']*100

In [104]:
del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

In [105]:
crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,300,15,3,2411,2465,75.000000,80.000000,100.000000,40.812941,87.058824
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [106]:
con_list = ['강간검거율','강도검거율','절도검거율','살인검거율','폭력검거율']

for column in con_list:
    crime_anal.loc[crime_anal[column] > 100, column] = 100

In [107]:
crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,300,15,3,2411,2465,75.000000,80.000000,100.000000,40.812941,87.058824
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157

In [108]:
crime_anal.rename(columns = {'강간 발생':'강간','강도 발생':'강도','살인 발생':'살인','절도 발생':'절도','폭력 발생':'폭력'},
                 inplace = True)

In [109]:
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,300,15,3,2411,2465,75.000000,80.000000,100.000000,40.812941,87.058824
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157